[build]
  command = "npm run build"
  publish = "dist"

# Specific redirect for shared wishlist pages
[[redirects]]
  from = "/wishlist/*/shared"
  to = "/index.html"
  status = 200
  force = true

# General redirect for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 